services:
  tipsfrontend:
    container_name: bilkro-frontend
    restart: unless-stopped
    build: .
    image: bilkro
    networks:
      - nginxproxymanager_default
    ports:
      - "3003:3000"

networks:
  nginxproxymanager_default:
    name: nginxproxymanager_default
    external: true